#ifndef H_RAZORBEARD_EVENTS
#define H_RAZORBEARD_EVENTS

#include "willis.h"

enum rzb_default_widgets_event_state
{
	RZB_STATE_NONE = WILLIS_STATE_NONE,
	RZB_STATE_PRESS = WILLIS_STATE_PRESS,
	RZB_STATE_RELEASE = WILLIS_STATE_RELEASE,
};

enum rzb_default_widgets_events
{
	RZB_NONE = WILLIS_NONE,

	RZB_MOUSE_CLICK_LEFT = WILLIS_MOUSE_CLICK_LEFT,
	RZB_MOUSE_CLICK_RIGHT = WILLIS_MOUSE_CLICK_RIGHT,
	RZB_MOUSE_CLICK_MIDDLE = WILLIS_MOUSE_CLICK_MIDDLE,
	RZB_MOUSE_WHEEL_UP = WILLIS_MOUSE_WHEEL_UP,
	RZB_MOUSE_WHEEL_DOWN = WILLIS_MOUSE_WHEEL_DOWN,
	RZB_MOUSE_MOTION = WILLIS_MOUSE_MOTION,

	RZB_KEY_ESCAPE = WILLIS_KEY_ESCAPE,
	RZB_KEY_BACKSPACE = WILLIS_KEY_BACKSPACE,
	RZB_KEY_TAB = WILLIS_KEY_TAB,
	RZB_KEY_ENTER = WILLIS_KEY_ENTER,
	RZB_KEY_SHIFT_LEFT = WILLIS_KEY_SHIFT_LEFT,
	RZB_KEY_SHIFT_RIGHT = WILLIS_KEY_SHIFT_RIGHT,
	RZB_KEY_CTRL_LEFT = WILLIS_KEY_CTRL_LEFT,
	RZB_KEY_CTRL_RIGHT = WILLIS_KEY_CTRL_RIGHT,
	RZB_KEY_DELETE = WILLIS_KEY_DELETE,
	RZB_KEY_HOME = WILLIS_KEY_HOME,
	RZB_KEY_END = WILLIS_KEY_END,
	RZB_KEY_PAGE_UP = WILLIS_KEY_PAGE_UP,
	RZB_KEY_PAGE_DOWN = WILLIS_KEY_PAGE_DOWN,
	RZB_KEY_UP = WILLIS_KEY_UP,
	RZB_KEY_DOWN = WILLIS_KEY_DOWN,
	RZB_KEY_LEFT = WILLIS_KEY_LEFT,
	RZB_KEY_RIGHT = WILLIS_KEY_RIGHT,
};

#endif
